# Generated by Django 5.2.5 on 2025-08-31 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0002_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who processed the refund",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_refunds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="payments.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="campaigns.campaignreward",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="original_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refunds",
                to="payments.transaction",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="refund_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refund_for",
                to="payments.transaction",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contribution",
                to="payments.transaction",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_id"], name="transaction_transac_5011c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="transaction_status_505a2f_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user"], name="transaction_user_id_b5bcfd_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["campaign"], name="transaction_campaig_4b781c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["initiated_at"], name="transaction_initiat_62bc61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["status"], name="refunds_status_2569d8_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["original_transaction"], name="refunds_origina_5cba21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["created_at"], name="refunds_created_7e4196_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(fields=["user"], name="contributio_user_id_4bc8cf_idx"),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["campaign"], name="contributio_campaig_99c07e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["created_at"], name="contributio_created_96604a_idx"
            ),
        ),
    ]
