# Generated by Django 5.2.5 on 2025-08-31 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("production", "Production Costs"),
                            ("equipment", "Equipment & Technology"),
                            ("personnel", "Personnel & Cast"),
                            ("marketing", "Marketing & Promotion"),
                            ("post_production", "Post-Production"),
                            ("distribution", "Distribution & Release"),
                            ("contingency", "Contingency Fund"),
                            ("other", "Other Expenses"),
                        ],
                        help_text="Type of fund allocation",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of how funds will be used"),
                ),
                (
                    "budgeted_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Budgeted amount for this allocation in LKR",
                        max_digits=15,
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Actual amount spent in this allocation",
                        max_digits=15,
                    ),
                ),
                (
                    "percentage_of_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of total funding for this allocation",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_allocations",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funding Allocation",
                "verbose_name_plural": "Funding Allocations",
                "db_table": "funding_allocations",
                "ordering": ["percentage_of_total"],
            },
        ),
        migrations.CreateModel(
            name="FundingAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_contributions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of contributions received"
                    ),
                ),
                (
                    "average_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Average contribution amount",
                        max_digits=10,
                    ),
                ),
                (
                    "median_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Median contribution amount",
                        max_digits=10,
                    ),
                ),
                (
                    "largest_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Largest single contribution received",
                        max_digits=15,
                    ),
                ),
                (
                    "unique_backers",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of unique backers"
                    ),
                ),
                (
                    "repeat_backers",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of repeat backers"
                    ),
                ),
                (
                    "new_backers",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of new backers"
                    ),
                ),
                (
                    "view_to_backer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage of viewers who became backers",
                        max_digits=5,
                    ),
                ),
                (
                    "top_locations",
                    models.JSONField(
                        blank=True, default=list, help_text="Top contributing locations"
                    ),
                ),
                (
                    "payment_method_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Distribution of contributions by payment method",
                    ),
                ),
                (
                    "peak_funding_day",
                    models.DateField(
                        blank=True, help_text="Day with highest funding", null=True
                    ),
                ),
                (
                    "peak_funding_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Highest funding amount in a single day",
                        max_digits=15,
                    ),
                ),
                (
                    "projected_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Projected date to reach funding goal",
                        null=True,
                    ),
                ),
                (
                    "funding_velocity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Average daily funding rate",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_analytics",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funding Analytics",
                "verbose_name_plural": "Funding Analytics",
                "db_table": "funding_analytics",
            },
        ),
        migrations.CreateModel(
            name="FundingMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Milestone title", max_length=200),
                ),
                ("description", models.TextField(help_text="Milestone description")),
                (
                    "funding_target",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Funding target for this milestone in LKR",
                        max_digits=15,
                    ),
                ),
                (
                    "is_achieved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this milestone has been achieved",
                    ),
                ),
                (
                    "achieved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the milestone was achieved",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the milestone"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_milestones",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funding Milestone",
                "verbose_name_plural": "Funding Milestones",
                "db_table": "funding_milestones",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FundingRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Funding"),
                            ("follow_up", "Follow-up Funding"),
                            ("emergency", "Emergency Funding"),
                            ("completion", "Completion Funding"),
                        ],
                        default="initial",
                        help_text="Type of funding round",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the funding round", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the funding round"),
                ),
                (
                    "funding_goal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Funding goal for this round in LKR",
                        max_digits=15,
                    ),
                ),
                (
                    "current_funding",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current amount raised in this round",
                        max_digits=15,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Start date of the funding round"),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="End date of the funding round"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this funding round is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_rounds",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funding Round",
                "verbose_name_plural": "Funding Rounds",
                "db_table": "funding_rounds",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="FundingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the progress record")),
                (
                    "total_funding",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total funding at this date",
                        max_digits=15,
                    ),
                ),
                (
                    "daily_funding",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Funding received on this date",
                        max_digits=15,
                    ),
                ),
                (
                    "backer_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of backers at this date"
                    ),
                ),
                (
                    "new_backers",
                    models.PositiveIntegerField(
                        default=0, help_text="New backers on this date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_progress",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funding Progress",
                "verbose_name_plural": "Funding Progress",
                "db_table": "funding_progress",
                "ordering": ["date"],
                "unique_together": {("campaign", "date")},
            },
        ),
    ]
