# Generated by Django 5.2.5 on 2025-08-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Campaign title", max_length=200)),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Campaign subtitle or tagline",
                        max_length=300,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed campaign description"),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Brief campaign summary", max_length=500
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        help_text="Campaign cover image", upload_to="campaign_covers/"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Campaign video URL (YouTube, Vimeo, etc.)",
                    ),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True, default=list, help_text="List of gallery image URLs"
                    ),
                ),
                (
                    "funding_goal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Campaign funding goal in LKR",
                        max_digits=15,
                    ),
                ),
                (
                    "current_funding",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current amount raised",
                        max_digits=15,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Campaign start date and time"),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="Campaign end date and time"),
                ),
                (
                    "estimated_completion_date",
                    models.DateField(help_text="Estimated project completion date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("funded", "Funded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        help_text="Current campaign status",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_for_review",
                    models.DateTimeField(
                        blank=True,
                        help_text="When campaign was submitted for review",
                        null=True,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When campaign was reviewed", null=True
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, help_text="Admin review notes"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of campaign views"
                    ),
                ),
                (
                    "backer_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of unique backers"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of campaign tags"
                    ),
                ),
                (
                    "risks_and_challenges",
                    models.TextField(
                        blank=True, help_text="Potential risks and challenges"
                    ),
                ),
                (
                    "team_members",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of team member information",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "db_table": "campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Category description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class or identifier", max_length=50
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this category is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campaign Category",
                "verbose_name_plural": "Campaign Categories",
                "db_table": "campaign_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CampaignComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Comment content")),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this comment is approved and visible",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campaign Comment",
                "verbose_name_plural": "Campaign Comments",
                "db_table": "campaign_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Reward title", max_length=200)),
                ("description", models.TextField(help_text="Reward description")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum contribution amount for this reward",
                        max_digits=10,
                    ),
                ),
                (
                    "max_backers",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of backers for this reward (null for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "current_backers",
                    models.PositiveIntegerField(
                        default=0, help_text="Current number of backers for this reward"
                    ),
                ),
                (
                    "estimated_delivery",
                    models.DateField(
                        help_text="Estimated delivery date for this reward"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this reward is currently available",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campaign Reward",
                "verbose_name_plural": "Campaign Rewards",
                "db_table": "campaign_rewards",
                "ordering": ["amount"],
            },
        ),
        migrations.CreateModel(
            name="CampaignUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Update title", max_length=200)),
                ("content", models.TextField(help_text="Update content")),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this update is visible to all backers",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campaign Update",
                "verbose_name_plural": "Campaign Updates",
                "db_table": "campaign_updates",
                "ordering": ["-created_at"],
            },
        ),
    ]
