# Generated by Django 5.2.5 on 2025-08-31 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="creator",
            field=models.ForeignKey(
                help_text="Campaign creator",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who reviewed the campaign",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="category",
            field=models.ForeignKey(
                help_text="Campaign category",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="campaigns.campaigncategory",
            ),
        ),
        migrations.AddField(
            model_name="campaigncomment",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaigncomment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent comment for replies",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="campaigns.campaigncomment",
            ),
        ),
        migrations.AddField(
            model_name="campaigncomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaignreward",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rewards",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaignupdate",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["status"], name="campaigns_status_a03570_idx"),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["category"], name="campaigns_categor_1a20f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["start_date"], name="campaigns_start_d_5c2c6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["end_date"], name="campaigns_end_dat_6aaba4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["funding_goal"], name="campaigns_funding_a85855_idx"
            ),
        ),
    ]
