# Generated by Django 5.2.5 on 2025-09-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Campaign cover image",
                null=True,
                upload_to="campaign_covers/",
            ),
        ),
    ]
