# Generated by Django 5.2.5 on 2025-08-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KYCComplianceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("aml", "Anti-Money Laundering"),
                            ("ctf", "Counter-Terrorism Financing"),
                            ("sanctions", "Sanctions Screening"),
                            ("pep", "Politically Exposed Person"),
                            ("adverse_media", "Adverse Media Screening"),
                            ("risk_assessment", "Risk Assessment"),
                        ],
                        help_text="Type of compliance check",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("requires_review", "Requires Review"),
                        ],
                        default="pending",
                        help_text="Status of the compliance check",
                        max_length=20,
                    ),
                ),
                (
                    "check_provider",
                    models.CharField(
                        blank=True,
                        help_text="Provider used for the compliance check",
                        max_length=100,
                    ),
                ),
                (
                    "check_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference ID from the compliance check",
                        max_length=100,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Risk score from the check (0-100)",
                        null=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        help_text="Risk level determined by the check",
                        max_length=20,
                    ),
                ),
                (
                    "check_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw data from the compliance check",
                    ),
                ),
                (
                    "initiated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the check was initiated"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the check was completed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about the compliance check"
                    ),
                ),
                (
                    "findings",
                    models.TextField(
                        blank=True, help_text="Key findings from the compliance check"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KYC Compliance Check",
                "verbose_name_plural": "KYC Compliance Checks",
                "db_table": "kyc_compliance_checks",
                "ordering": ["initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("identity", "Identity Document"),
                            ("address_proof", "Address Proof"),
                            ("financial_proof", "Financial Proof"),
                            ("employment_proof", "Employment Proof"),
                            ("business_registration", "Business Registration"),
                            ("bank_statement", "Bank Statement"),
                            ("tax_document", "Tax Document"),
                            ("other", "Other"),
                        ],
                        help_text="Type of document",
                        max_length=50,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        help_text="Uploaded document file", upload_to="kyc_documents/"
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        help_text="Name/description of the document", max_length=200
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Document identification number",
                        max_length=100,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, help_text="Document issue date", null=True
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Document expiry date", null=True
                    ),
                ),
                (
                    "issuing_authority",
                    models.CharField(
                        blank=True,
                        help_text="Authority that issued the document",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("requires_review", "Requires Review"),
                        ],
                        default="pending",
                        help_text="Verification status of this document",
                        max_length=20,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When document was verified", null=True
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, help_text="Notes from document verification"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection if applicable"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of the document file",
                        max_length=64,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the document file",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KYC Document",
                "verbose_name_plural": "KYC Documents",
                "db_table": "kyc_documents",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="KYCRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Verification"),
                            ("enhanced", "Enhanced Verification"),
                            ("corporate", "Corporate Verification"),
                        ],
                        default="basic",
                        help_text="Level of KYC verification required",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            (
                                "requires_additional_info",
                                "Requires Additional Information",
                            ),
                        ],
                        default="pending",
                        help_text="Current status of KYC request",
                        max_length=30,
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        help_text="Legal name as per official documents", max_length=255
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(help_text="Date of birth for verification"),
                ),
                (
                    "nationality",
                    models.CharField(
                        help_text="Nationality of the user", max_length=100
                    ),
                ),
                (
                    "residential_address",
                    models.TextField(help_text="Current residential address"),
                ),
                (
                    "identity_document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID Card"),
                            ("passport", "Passport"),
                            ("drivers_license", "Driver's License"),
                            ("birth_certificate", "Birth Certificate"),
                        ],
                        help_text="Type of identity document provided",
                        max_length=50,
                    ),
                ),
                (
                    "identity_document_number",
                    models.CharField(
                        help_text="Identity document number", max_length=100
                    ),
                ),
                (
                    "identity_document_expiry",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date of identity document",
                        null=True,
                    ),
                ),
                (
                    "address_proof_type",
                    models.CharField(
                        choices=[
                            ("utility_bill", "Utility Bill"),
                            ("bank_statement", "Bank Statement"),
                            ("rental_agreement", "Rental Agreement"),
                            ("property_deed", "Property Deed"),
                            ("government_letter", "Government Letter"),
                        ],
                        help_text="Type of address proof document",
                        max_length=50,
                    ),
                ),
                (
                    "address_proof_date",
                    models.DateField(help_text="Date of address proof document"),
                ),
                (
                    "source_of_funds",
                    models.CharField(
                        choices=[
                            ("employment", "Employment Income"),
                            ("business", "Business Income"),
                            ("investment", "Investment Income"),
                            ("inheritance", "Inheritance"),
                            ("gift", "Gift"),
                            ("other", "Other"),
                        ],
                        help_text="Primary source of funds",
                        max_length=100,
                    ),
                ),
                (
                    "annual_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual income amount",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employed", "Employed"),
                            ("self_employed", "Self-Employed"),
                            ("unemployed", "Unemployed"),
                            ("student", "Student"),
                            ("retired", "Retired"),
                        ],
                        help_text="Current employment status",
                        max_length=50,
                    ),
                ),
                (
                    "employer_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of employer or company",
                        max_length=200,
                    ),
                ),
                (
                    "political_exposure",
                    models.BooleanField(
                        default=False, help_text="Whether user has political exposure"
                    ),
                ),
                (
                    "politically_exposed_person",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user is a politically exposed person",
                    ),
                ),
                (
                    "sanctions_check",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user passed sanctions screening",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When KYC was submitted"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When KYC was reviewed", null=True
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Notes from the review process"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection if applicable"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KYC Request",
                "verbose_name_plural": "KYC Requests",
                "db_table": "kyc_requests",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="KYCVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("identity", "Identity Verification"),
                            ("address", "Address Verification"),
                            ("financial", "Financial Verification"),
                            ("document", "Document Verification"),
                            ("sanctions", "Sanctions Screening"),
                            ("pep", "PEP Screening"),
                        ],
                        help_text="Type of verification",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("requires_review", "Requires Review"),
                        ],
                        default="pending",
                        help_text="Status of this verification",
                        max_length=20,
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        blank=True,
                        help_text="Method used for verification",
                        max_length=100,
                    ),
                ),
                (
                    "verification_provider",
                    models.CharField(
                        blank=True,
                        help_text="External provider used for verification",
                        max_length=100,
                    ),
                ),
                (
                    "verification_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference ID from verification provider",
                        max_length=100,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether verification was successful"
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence score from verification (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "verification_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw data from verification process",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When verification started"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When verification was completed",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about the verification process"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if verification failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KYC Verification",
                "verbose_name_plural": "KYC Verifications",
                "db_table": "kyc_verifications",
                "ordering": ["started_at"],
            },
        ),
    ]
