# Generated by Django 5.2.5 on 2025-08-31 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("kyc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="kycdocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who verified this document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_kyc_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kycrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who reviewed the KYC request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_kyc_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kycrequest",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kyc_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kycdocument",
            name="kyc_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="kyc.kycrequest",
            ),
        ),
        migrations.AddField(
            model_name="kyccompliancecheck",
            name="kyc_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_checks",
                to="kyc.kycrequest",
            ),
        ),
        migrations.AddField(
            model_name="kycverification",
            name="kyc_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifications",
                to="kyc.kycrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="kycrequest",
            index=models.Index(fields=["status"], name="kyc_request_status_5b6087_idx"),
        ),
        migrations.AddIndex(
            model_name="kycrequest",
            index=models.Index(
                fields=["verification_level"], name="kyc_request_verific_394d99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycrequest",
            index=models.Index(
                fields=["submitted_at"], name="kyc_request_submitt_0a13f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycdocument",
            index=models.Index(
                fields=["document_type"], name="kyc_documen_documen_9c13cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycdocument",
            index=models.Index(fields=["status"], name="kyc_documen_status_355905_idx"),
        ),
        migrations.AddIndex(
            model_name="kycdocument",
            index=models.Index(
                fields=["created_at"], name="kyc_documen_created_4f4505_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kyccompliancecheck",
            index=models.Index(
                fields=["check_type"], name="kyc_complia_check_t_716508_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kyccompliancecheck",
            index=models.Index(fields=["status"], name="kyc_complia_status_37a538_idx"),
        ),
        migrations.AddIndex(
            model_name="kyccompliancecheck",
            index=models.Index(
                fields=["risk_level"], name="kyc_complia_risk_le_6c9c15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kyccompliancecheck",
            index=models.Index(
                fields=["initiated_at"], name="kyc_complia_initiat_6ab0d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycverification",
            index=models.Index(
                fields=["verification_type"], name="kyc_verific_verific_5410d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycverification",
            index=models.Index(fields=["status"], name="kyc_verific_status_0b0fb6_idx"),
        ),
        migrations.AddIndex(
            model_name="kycverification",
            index=models.Index(
                fields=["started_at"], name="kyc_verific_started_03bdc3_idx"
            ),
        ),
    ]
